(* Instaparse grammar for the conversion from textexport v3 of pdf *)
(* THIS GRAMMAR IS CUSTOM ONLY FOR THAT PARTICULAR FILE. THERE IS NO INTENTION ON BEING GENERAL *)
(* Don't use this as an authoritative answer on how to model data *)

poster = post*
post =
löpnummer                   (* id *)
län                         (* swedish region *)
kommun                      (* swedish municipality *)
socken                      (* swedish [state] church parish *)
föreningensnamn             (* name of the association *)
föreningensinstiftelseår    (* year of the association foundation *)
objekt                      (* ? *)
formavägande                (* *)
intressenter                (* *)
fastighetsbeteckning        (* *)
adress                      (* postal address *)
arkitekt                    (* architect *)
byggmästare                 (* *)
nybyggnadsår                (* year of new/initial onstruction *)
miljö                       (* description of the environment of the place *)
renoveringombyggnad         (* renovation or reconstruction *)
byggnaderfunktioner         (* buildings/functions *)
verksamhetidag              (* current activities *)
tidigarefunktion            (* earlier functions / activities *)
litteratur                  (* litterature covering the association *)
arkivhandlingar             (* associations archives *)
källa                       (* source / reference *)
anmärkning                  (* note / comment *)

whitespace = #"\s"

löpnummer = <"Löpnummer"> <#" "?> #"\d+" <"\n"> (* löpnummer is always four digits, like 0123 *)

län = <"Län"> (<" "> #".+")? <"\n">             (* can be nothing, or one or two versal letters *)

kommun = <"Kommun"> (<" "> #".+")? <"\n">

socken = <"Socken"> (<" "> #".+")? <"\n">
föreningensnamn = <"Föreningens namn"> (<" "> #".+")? <"\n">
föreningensinstiftelseår = <"Föreningens instiftelseår"> (<" "> <#"\d+">)? <whitespace>* <"\n">
objekt = <"Objekt"> (<" "> #".+")? <"\n">

formavägande = <"Form av ägande"> #".*" <"\n">)
intressenterrad = (!fastighetshetsbeteckning  #".*" <"\n">)
intressenter = <"Intressenter"> intressenterrad*
fastighetsbeteckning = <"Fastighetsbeteckning"> (<" "> #".+")? <"\n">
adress = <"Adress"> (<" "> #".+")? <"\n">
arkitekt = <"Arkitekt"> (<" "> #".+")? <"\n">
byggmästare = <"Byggmästare"> (<" "> #".+")? <"\n">
nybyggnadsår = <"Nybyggnadsår"> (<" "> <#".+">)? <"\n">
miljö = <"Miljö"> (<" "> #".+")? <"\n">
renoveringombyggnad = <"Renovering, ombyggnad"> (#" .+")? <"\n">
byggnaderfunktionerrad = (!verksamhetidag #".*" <"\n">)
byggnaderfunktioner = <"Byggnader, funktioner"> byggnaderfunktionerrad*
verksamhetidag = <"Verksamhet idag"> (<" "> #".+")? <"\n">
tidigarefunktion = <"Tidigare funktion"> (#".+")? <"\n">
litteratur = <"Litteratur"> (<" "> #".+")? <"\n">

arkivrad =  (!källa #".*\n")
arkivtoken = #".*Arkivhandlingar\nArkivhandlingar\n" (* the PDF has a page break in this word, hence it occurs twice *)
arkivhandlingar = arkivtoken arkivrad*
källa = <"Källa"> (<" "> #".+")? <"\n">?
anmärkningtoken = <"Anmärkning">
anmärkningrad = (!löpnummer #".+\n")
anmärkning = (anmärkningtoken | anmärkningrad*)
