<poster> = post*
post =
löpnummer
län
kommun
socken
föreningensnamn
föreningensinstiftelseår
objekt
formavägande
intressenter
fastighetsbeteckning
adress
arkitekt                    
byggmästare                 
nybyggnadsår                
miljö                       
renoveringombyggnad         
byggnaderfunktioner         
verksamhetidag              
tidigarefunktion            
litteratur                  
arkivhandlingar             
källa                       
anmärkning                  

<fritext> = ((<" ">? #".+"? <"\n">) | <"\n">)

<enrad>  =  ((<" ">  #".+"? <"\n">) | <"\n">)

löpnummer = <"Löpnummer"> <" ">? #"\d+" <"\n"> 
län = <"Län"> enrad
kommun = <"Kommun"> enrad
socken = <"Socken"> enrad
föreningensnamn = <"Föreningens namn"> enrad
föreningensinstiftelseår = <"Föreningens instiftelseår"> enrad
objekt = <"Objekt"> enrad
formavägande = <"Form av ägande"> enrad
<intressenterrad> = (!fastighetsbeteckning fritext)
intressenter = <"Intressenter"> intressenterrad*
fastighetsbeteckning = <"Fastighetsbeteckning"> enrad
adress = <"Adress"> enrad
arkitekt = <"Arkitekt"> enrad
byggmästare = <"Byggmästare"> enrad
nybyggnadsår = <"Nybyggnadsår"> enrad
miljö = <"Miljö"> enrad
<rorad> = (!byggnaderfunktioner fritext)
renoveringombyggnad = <"Renovering, ombyggnad"> enrad rorad*
<byggnaderfunktionerrad> = (!verksamhetidag fritext)
byggnaderfunktioner = <"Byggnader, funktioner"> enrad byggnaderfunktionerrad*
<verksamhetidagrad> = (!tidigarefunktion fritext)
verksamhetidag = <"Verksamhet idag"> enrad verksamhetidagrad*
<tidigarefunktionrad> = (!litteratur fritext)
tidigarefunktion = <"Tidigare funktion"> enrad tidigarefunktionrad*
<littrad> = (!arkivhandlingar fritext)
litteratur = <"Litteratur"> enrad littrad*
<arkivrad> =  (!källa fritext)
arkivtoken = <"Arkivhandlingar\nArkivhandlingar\n">
arkivhandlingar = <arkivtoken> arkivrad*
<källarad> = (!anmärkning fritext)
källa = <"Källa"> enrad källarad*
anmärkningtoken = <"Anmärkning">
<anmärkningrad> = (!löpnummer <" ">? #".*" <"\n">)
anmärkning = (<anmärkningtoken> enrad anmärkningrad*)
